{
    "today_available_experts": [],
    "customers": {
        "app_customers": [
            {
                "id": 31,
                "business_id": 2,
                "first_Name": "Himel",
                "last_Name": "hossain",
                "phone": "01777777733",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "himelahmszed@gmail.com",
                "stripe_id": null,
                "email_verified_at": "02-11-2024 19:48:36",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "02-11-2024 19:48:36",
                "updated_at": "02-11-2024 19:48:36",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 37,
                "business_id": null,
                "first_Name": "Rifat",
                "last_Name": "Al",
                "phone": "01555555555",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "rifat_customer1@gmail.com",
                "stripe_id": null,
                "email_verified_at": "04-11-2024 16:43:24",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "04-11-2024 16:43:24",
                "updated_at": "04-11-2024 16:43:24",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 40,
                "business_id": null,
                "first_Name": "mozammal",
                "last_Name": "hossain",
                "phone": "01777777767",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "mozammalhossain333@gmail.com",
                "stripe_id": null,
                "email_verified_at": "07-11-2024 06:56:27",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "07-11-2024 06:56:27",
                "updated_at": "09-11-2024 23:50:40",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 47,
                "business_id": 2,
                "first_Name": "asdasd",
                "last_Name": "asdasd",
                "phone": "12345675435",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "asdasd@aaaaa.ff",
                "stripe_id": null,
                "email_verified_at": "09-11-2024 06:49:10",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "09-11-2024 06:49:10",
                "updated_at": "09-11-2024 06:49:10",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 54,
                "business_id": null,
                "first_Name": "Rifat",
                "last_Name": "khan",
                "phone": "01555555555",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "rifat_khan@gmail.com",
                "stripe_id": null,
                "email_verified_at": "10-11-2024 09:15:13",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "10-11-2024 09:15:13",
                "updated_at": "10-11-2024 09:15:13",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            }
        ],
        "walk_in_customers": [
            {
                "id": 53,
                "business_id": 2,
                "first_Name": "asd",
                "last_Name": "asd",
                "phone": null,
                "image": null,
                "is_walk_in_customer": 1,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": null,
                "stripe_id": null,
                "email_verified_at": null,
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "09-11-2024 18:11:36",
                "updated_at": "09-11-2024 18:11:36",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            }
        ],
        "repeated_customers": [
            {
                "id": 31,
                "business_id": 2,
                "first_Name": "Himel",
                "last_Name": "hossain",
                "phone": "01777777733",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "himelahmszed@gmail.com",
                "stripe_id": null,
                "email_verified_at": "02-11-2024 19:48:36",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "02-11-2024 19:48:36",
                "updated_at": "02-11-2024 19:48:36",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 37,
                "business_id": null,
                "first_Name": "Rifat",
                "last_Name": "Al",
                "phone": "01555555555",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "rifat_customer1@gmail.com",
                "stripe_id": null,
                "email_verified_at": "04-11-2024 16:43:24",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "04-11-2024 16:43:24",
                "updated_at": "04-11-2024 16:43:24",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 40,
                "business_id": null,
                "first_Name": "mozammal",
                "last_Name": "hossain",
                "phone": "01777777767",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "mozammalhossain333@gmail.com",
                "stripe_id": null,
                "email_verified_at": "07-11-2024 06:56:27",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "07-11-2024 06:56:27",
                "updated_at": "09-11-2024 23:50:40",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 47,
                "business_id": 2,
                "first_Name": "asdasd",
                "last_Name": "asdasd",
                "phone": "12345675435",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "asdasd@aaaaa.ff",
                "stripe_id": null,
                "email_verified_at": "09-11-2024 06:49:10",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "09-11-2024 06:49:10",
                "updated_at": "09-11-2024 06:49:10",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            },
            {
                "id": 54,
                "business_id": null,
                "first_Name": "Rifat",
                "last_Name": "khan",
                "phone": "01555555555",
                "image": null,
                "is_walk_in_customer": 0,
                "address_line_1": null,
                "address_line_2": null,
                "country": null,
                "city": null,
                "postcode": null,
                "lat": null,
                "long": null,
                "email": "rifat_khan@gmail.com",
                "stripe_id": null,
                "email_verified_at": "10-11-2024 09:15:13",
                "is_active": "1",
                "created_by": null,
                "login_attempts": 0,
                "last_failed_login_attempt_at": null,
                "background_image": null,
                "deleted_at": null,
                "created_at": "10-11-2024 09:15:13",
                "updated_at": "10-11-2024 09:15:13",
                "weekly_minimum_days": 0,
                "weekly_minimum_hours": 0
            }
        ]
    },
    "bookings": {
        "all": 10,
        "pending": 8,
        "confirmed": 0,
        "check_in": 2,
        "rejected_by_client": 0,
        "rejected_by_garage_owner": 0,
        "arrived": 0,
        "converted_to_job": 0
    },
    "revenue": {
        "app_customer_revenue": null,
        "walk_in_customer_revenue": null
    },
    "top_services": [
        {
            "id": 383,
            "name": "Classic European Facial",
            "description": "A deep-cleansing facial that exfoliates, extracts impurities, and nourishes the skin, leaving it smooth and refreshed",
            "service_id": 29,
            "is_fixed_price": 1,
            "business_id": 2,
            "service_time_in_minute": 45,
            "deleted_at": null,
            "created_at": "01-11-2024 10:38:44",
            "updated_at": "01-11-2024 10:38:44",
            "default_price": 50,
            "price": "50.00",
            "all_sales_count": 44
        },
        {
            "id": 378,
            "name": "Swedish Massage",
            "description": "A relaxing, full-body massage that uses light to medium pressure, promoting relaxation and stress relief",
            "service_id": 24,
            "is_fixed_price": 1,
            "business_id": 2,
            "service_time_in_minute": 30,
            "deleted_at": null,
            "created_at": "31-10-2024 14:20:29",
            "updated_at": "01-11-2024 09:54:36",
            "default_price": 25,
            "price": "25.00",
            "all_sales_count": 23
        },
        {
            "id": 379,
            "name": "Deep Tissue Massage",
            "description": "Targets deeper muscle layers, perfect for chronic pain and muscle tension by applying more intense pressure",
            "service_id": 24,
            "is_fixed_price": 1,
            "business_id": 2,
            "service_time_in_minute": 30,
            "deleted_at": null,
            "created_at": "31-10-2024 14:21:04",
            "updated_at": "01-11-2024 09:53:58",
            "default_price": 45,
            "price": "45.00",
            "all_sales_count": 11
        },
        {
            "id": 382,
            "name": "Prenatal Massage",
            "description": "Specifically designed for pregnant women, focusing on relieving pregnancy-related discomfort and improving circulation",
            "service_id": 24,
            "is_fixed_price": 1,
            "business_id": 2,
            "service_time_in_minute": 30,
            "deleted_at": null,
            "created_at": "31-10-2024 14:22:49",
            "updated_at": "01-11-2024 09:54:22",
            "default_price": 30,
            "price": "30.00",
            "all_sales_count": 9
        },
        {
            "id": 380,
            "name": "Hot Stone Massage",
            "description": "Heated stones are placed on key points of the body, enhancing relaxation and easing muscle stiffness",
            "service_id": 24,
            "is_fixed_price": 1,
            "business_id": 2,
            "service_time_in_minute": 30,
            "deleted_at": null,
            "created_at": "31-10-2024 14:21:48",
            "updated_at": "01-11-2024 09:54:13",
            "default_price": 20,
            "price": "20.00",
            "all_sales_count": 8
        }
    ],
    "busy_slots": "20",
    "booked_slots": "352",
    "experts": [
        {
            "id": 38,
            "business_id": 2,
            "first_Name": "Rony",
            "last_Name": "Mia",
            "phone": "01555555555",
            "image": null,
            "is_walk_in_customer": 0,
            "address_line_1": null,
            "address_line_2": null,
            "country": null,
            "city": null,
            "postcode": null,
            "lat": null,
            "long": null,
            "email": "rony_barber@gmail.com",
            "stripe_id": null,
            "email_verified_at": "04-11-2024 17:06:51",
            "is_active": "1",
            "created_by": null,
            "login_attempts": 0,
            "last_failed_login_attempt_at": null,
            "background_image": null,
            "deleted_at": null,
            "created_at": "04-11-2024 17:06:51",
            "updated_at": "05-11-2024 12:15:44",
            "weekly_minimum_days": 5,
            "weekly_minimum_hours": 40,
            "this_month_revenue": 0,
            "last_month_revenue": 0,
            "total_bookings": "73",
            "upcoming_bookings_today": [],
            "upcoming_bookings": [],
            "all_services": [
                {
                    "id": 381,
                    "name": "Aromatherapy Massage",
                    "description": "Combines massage with the use of essential oils to boost physical and emotional well-being",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:22:20",
                    "updated_at": "01-11-2024 09:50:55",
                    "default_price": 40,
                    "price": "40.00"
                },
                {
                    "id": 383,
                    "name": "Classic European Facial",
                    "description": "A deep-cleansing facial that exfoliates, extracts impurities, and nourishes the skin, leaving it smooth and refreshed",
                    "service_id": 29,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 45,
                    "deleted_at": null,
                    "created_at": "01-11-2024 10:38:44",
                    "updated_at": "01-11-2024 10:38:44",
                    "default_price": 50,
                    "price": "50.00"
                },
                {
                    "id": 379,
                    "name": "Deep Tissue Massage",
                    "description": "Targets deeper muscle layers, perfect for chronic pain and muscle tension by applying more intense pressure",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:21:04",
                    "updated_at": "01-11-2024 09:53:58",
                    "default_price": 45,
                    "price": "45.00"
                },
                {
                    "id": 380,
                    "name": "Hot Stone Massage",
                    "description": "Heated stones are placed on key points of the body, enhancing relaxation and easing muscle stiffness",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:21:48",
                    "updated_at": "01-11-2024 09:54:13",
                    "default_price": 20,
                    "price": "20.00"
                },
                {
                    "id": 382,
                    "name": "Prenatal Massage",
                    "description": "Specifically designed for pregnant women, focusing on relieving pregnancy-related discomfort and improving circulation",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:22:49",
                    "updated_at": "01-11-2024 09:54:22",
                    "default_price": 30,
                    "price": "30.00"
                },
                {
                    "id": 378,
                    "name": "Swedish Massage",
                    "description": "A relaxing, full-body massage that uses light to medium pressure, promoting relaxation and stress relief",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:20:29",
                    "updated_at": "01-11-2024 09:54:36",
                    "default_price": 25,
                    "price": "25.00"
                }
            ],
            "average_rating": 0,
            "bookings": {
                "all": 0,
                "pending": 0,
                "confirmed": 0,
                "check_in": 0,
                "rejected_by_client": 0,
                "rejected_by_garage_owner": 0,
                "arrived": 0,
                "converted_to_job": 0
            },
            "revenue": 821.75,
            "busy_slots": [],
            "appointment_trends": [],
            "all_booked_slots": "352",
            "average_booked_slots_time": 48.889499999999998181010596454143524169921875,
            "booking_distribution": {
                "self_booking": 14,
                "admin_panel_booking": 90,
                "walk_in_customer_booking": 4
            },
            "translation": [
                {
                    "id": 30,
                    "user_id": 38,
                    "language": "ar",
                    "first_Name": "\u0631\u0648\u0646\u064a",
                    "last_Name": "Mia",
                    "created_at": "05-11-2024 12:15:45",
                    "updated_at": "05-11-2024 12:15:45"
                }
            ]
        },
        {
            "id": 39,
            "business_id": 2,
            "first_Name": "Mozammal",
            "last_Name": "Hossain",
            "phone": "01777777734",
            "image": null,
            "is_walk_in_customer": 0,
            "address_line_1": "Dhaka, Bangladesh",
            "address_line_2": null,
            "country": "Bangladesh",
            "city": "Dhaka",
            "postcode": "1330",
            "lat": null,
            "long": null,
            "email": "mozammal_expert@gmail.com",
            "stripe_id": null,
            "email_verified_at": "06-11-2024 13:18:04",
            "is_active": "1",
            "created_by": null,
            "login_attempts": 0,
            "last_failed_login_attempt_at": null,
            "background_image": null,
            "deleted_at": null,
            "created_at": "06-11-2024 13:18:04",
            "updated_at": "07-11-2024 10:59:30",
            "weekly_minimum_days": 5,
            "weekly_minimum_hours": 30,
            "this_month_revenue": 0,
            "last_month_revenue": 0,
            "total_bookings": "63",
            "upcoming_bookings_today": [
                {
                    "id": 235,
                    "expert_id": 39,
                    "booked_slots": [
                        "8:00 PM",
                        "8:15 PM",
                        "8:30 PM",
                        "8:45 PM"
                    ],
                    "booking_type": "walk_in_customer_booking",
                    "pre_booking_id": null,
                    "garage_id": 2,
                    "customer_id": 53,
                    "additional_information": null,
                    "reason": null,
                    "coupon_discount_type": "fixed",
                    "coupon_discount_amount": 0,
                    "discount_type": "percentage",
                    "discount_amount": 0,
                    "tip_type": "fixed",
                    "tip_amount": 0,
                    "price": 70,
                    "final_price": 80.5,
                    "coupon_code": null,
                    "payment_intent_id": null,
                    "job_start_date": "10-11-2024",
                    "status": "pending",
                    "created_by": 8,
                    "created_from": "garage_owner_side",
                    "created_at": "09-11-2024 18:11:36",
                    "updated_at": "09-11-2024 18:11:36",
                    "deleted_at": null,
                    "payment_status": "pending",
                    "payment_method": null,
                    "next_visit_date": null,
                    "send_notification": null,
                    "vat_percentage": 15,
                    "vat_amount": 10.5,
                    "booking_from": "quick_booking",
                    "expert_note": null,
                    "receptionist_note": null,
                    "joining_date": null,
                    "main_price": 80.5
                },
                {
                    "id": 238,
                    "expert_id": 39,
                    "booked_slots": [
                        "3:30 PM",
                        "3:45 PM",
                        "4:00 PM"
                    ],
                    "booking_type": "self_booking",
                    "pre_booking_id": null,
                    "garage_id": 2,
                    "customer_id": 54,
                    "additional_information": "ff",
                    "reason": null,
                    "coupon_discount_type": "fixed",
                    "coupon_discount_amount": 0,
                    "discount_type": "fixed",
                    "discount_amount": 0,
                    "tip_type": "fixed",
                    "tip_amount": 0,
                    "price": 50,
                    "final_price": 57.5,
                    "coupon_code": null,
                    "payment_intent_id": "pi_3QJXL1Bo1KvubNxp2b8Cca3z",
                    "job_start_date": "10-11-2024",
                    "status": "pending",
                    "created_by": 54,
                    "created_from": "customer_side",
                    "created_at": "10-11-2024 09:21:41",
                    "updated_at": "10-11-2024 09:21:42",
                    "deleted_at": null,
                    "payment_status": "complete",
                    "payment_method": "stripe",
                    "next_visit_date": null,
                    "send_notification": null,
                    "vat_percentage": 15,
                    "vat_amount": 7.5,
                    "booking_from": null,
                    "expert_note": null,
                    "receptionist_note": null,
                    "joining_date": null,
                    "main_price": 57.5
                },
                {
                    "id": 239,
                    "expert_id": 39,
                    "booked_slots": [
                        "4:15 PM",
                        "4:30 PM",
                        "4:45 PM"
                    ],
                    "booking_type": "self_booking",
                    "pre_booking_id": null,
                    "garage_id": 2,
                    "customer_id": 54,
                    "additional_information": null,
                    "reason": null,
                    "coupon_discount_type": "fixed",
                    "coupon_discount_amount": 0,
                    "discount_type": "fixed",
                    "discount_amount": 0,
                    "tip_type": "fixed",
                    "tip_amount": 0,
                    "price": 50,
                    "final_price": 57.5,
                    "coupon_code": null,
                    "payment_intent_id": "pi_3QJXM2Bo1KvubNxp33IQ1Hxk",
                    "job_start_date": "10-11-2024",
                    "status": "pending",
                    "created_by": 54,
                    "created_from": "customer_side",
                    "created_at": "10-11-2024 09:22:45",
                    "updated_at": "10-11-2024 09:22:46",
                    "deleted_at": null,
                    "payment_status": "complete",
                    "payment_method": "stripe",
                    "next_visit_date": null,
                    "send_notification": null,
                    "vat_percentage": 15,
                    "vat_amount": 7.5,
                    "booking_from": null,
                    "expert_note": null,
                    "receptionist_note": null,
                    "joining_date": null,
                    "main_price": 57.5
                }
            ],
            "upcoming_bookings": [
                {
                    "id": 226,
                    "expert_id": 39,
                    "booked_slots": [
                        "9:00 AM",
                        "9:15 AM",
                        "9:30 AM"
                    ],
                    "booking_type": "self_booking",
                    "pre_booking_id": null,
                    "garage_id": 2,
                    "customer_id": 40,
                    "additional_information": null,
                    "reason": null,
                    "coupon_discount_type": "fixed",
                    "coupon_discount_amount": 0,
                    "discount_type": "fixed",
                    "discount_amount": 10.5,
                    "tip_type": "fixed",
                    "tip_amount": 0,
                    "price": 50,
                    "final_price": 45.4249999999999971578290569595992565155029296875,
                    "coupon_code": null,
                    "payment_intent_id": null,
                    "job_start_date": "11-11-2024",
                    "status": "pending",
                    "created_by": 40,
                    "created_from": "customer_side",
                    "created_at": "09-11-2024 16:13:42",
                    "updated_at": "09-11-2024 18:14:18",
                    "deleted_at": null,
                    "payment_status": "complete",
                    "payment_method": "cash",
                    "next_visit_date": null,
                    "send_notification": null,
                    "vat_percentage": 15,
                    "vat_amount": 5.92499999999999982236431605997495353221893310546875,
                    "booking_from": null,
                    "expert_note": null,
                    "receptionist_note": null,
                    "joining_date": null,
                    "main_price": 45.4249999999999971578290569595992565155029296875
                },
                {
                    "id": 234,
                    "expert_id": 39,
                    "booked_slots": [
                        "10:30 AM",
                        "10:45 AM",
                        "11:00 AM",
                        "11:15 AM",
                        "11:30 AM"
                    ],
                    "booking_type": "walk_in_customer_booking",
                    "pre_booking_id": null,
                    "garage_id": 2,
                    "customer_id": 52,
                    "additional_information": null,
                    "reason": null,
                    "coupon_discount_type": "fixed",
                    "coupon_discount_amount": 0,
                    "discount_type": "percentage",
                    "discount_amount": 0,
                    "tip_type": "fixed",
                    "tip_amount": 0,
                    "price": 75,
                    "final_price": 86.25,
                    "coupon_code": null,
                    "payment_intent_id": null,
                    "job_start_date": "11-11-2024",
                    "status": "pending",
                    "created_by": 8,
                    "created_from": "garage_owner_side",
                    "created_at": "09-11-2024 18:03:52",
                    "updated_at": "09-11-2024 18:03:52",
                    "deleted_at": null,
                    "payment_status": "pending",
                    "payment_method": "cash",
                    "next_visit_date": null,
                    "send_notification": 1,
                    "vat_percentage": 15,
                    "vat_amount": 11.25,
                    "booking_from": "slot_booking",
                    "expert_note": null,
                    "receptionist_note": null,
                    "joining_date": null,
                    "main_price": 86.25
                },
                {
                    "id": 237,
                    "expert_id": 39,
                    "booked_slots": [
                        "12:15 PM",
                        "12:30 PM",
                        "12:45 PM",
                        "1:00 PM",
                        "1:15 PM"
                    ],
                    "booking_type": "self_booking",
                    "pre_booking_id": null,
                    "garage_id": 2,
                    "customer_id": 40,
                    "additional_information": null,
                    "reason": null,
                    "coupon_discount_type": "fixed",
                    "coupon_discount_amount": 0,
                    "discount_type": "fixed",
                    "discount_amount": 0,
                    "tip_type": "fixed",
                    "tip_amount": 0,
                    "price": 95,
                    "final_price": 109.25,
                    "coupon_code": null,
                    "payment_intent_id": null,
                    "job_start_date": "11-11-2024",
                    "status": "pending",
                    "created_by": 40,
                    "created_from": "customer_side",
                    "created_at": "09-11-2024 23:51:51",
                    "updated_at": "09-11-2024 23:51:51",
                    "deleted_at": null,
                    "payment_status": "pending",
                    "payment_method": "cash",
                    "next_visit_date": null,
                    "send_notification": null,
                    "vat_percentage": 15,
                    "vat_amount": 14.25,
                    "booking_from": null,
                    "expert_note": null,
                    "receptionist_note": null,
                    "joining_date": null,
                    "main_price": 109.25
                }
            ],
            "all_services": [
                {
                    "id": 381,
                    "name": "Aromatherapy Massage",
                    "description": "Combines massage with the use of essential oils to boost physical and emotional well-being",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:22:20",
                    "updated_at": "01-11-2024 09:50:55",
                    "default_price": 40,
                    "price": "40.00"
                },
                {
                    "id": 383,
                    "name": "Classic European Facial",
                    "description": "A deep-cleansing facial that exfoliates, extracts impurities, and nourishes the skin, leaving it smooth and refreshed",
                    "service_id": 29,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 45,
                    "deleted_at": null,
                    "created_at": "01-11-2024 10:38:44",
                    "updated_at": "01-11-2024 10:38:44",
                    "default_price": 50,
                    "price": "50.00"
                },
                {
                    "id": 379,
                    "name": "Deep Tissue Massage",
                    "description": "Targets deeper muscle layers, perfect for chronic pain and muscle tension by applying more intense pressure",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:21:04",
                    "updated_at": "01-11-2024 09:53:58",
                    "default_price": 45,
                    "price": "45.00"
                },
                {
                    "id": 380,
                    "name": "Hot Stone Massage",
                    "description": "Heated stones are placed on key points of the body, enhancing relaxation and easing muscle stiffness",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:21:48",
                    "updated_at": "01-11-2024 09:54:13",
                    "default_price": 20,
                    "price": "20.00"
                },
                {
                    "id": 382,
                    "name": "Prenatal Massage",
                    "description": "Specifically designed for pregnant women, focusing on relieving pregnancy-related discomfort and improving circulation",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:22:49",
                    "updated_at": "01-11-2024 09:54:22",
                    "default_price": 30,
                    "price": "30.00"
                },
                {
                    "id": 378,
                    "name": "Swedish Massage",
                    "description": "A relaxing, full-body massage that uses light to medium pressure, promoting relaxation and stress relief",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:20:29",
                    "updated_at": "01-11-2024 09:54:36",
                    "default_price": 25,
                    "price": "25.00"
                }
            ],
            "average_rating": 0,
            "bookings": {
                "all": 6,
                "pending": 5,
                "confirmed": 0,
                "check_in": 1,
                "rejected_by_client": 0,
                "rejected_by_garage_owner": 0,
                "arrived": 0,
                "converted_to_job": 0
            },
            "revenue": 666.799999999999954525264911353588104248046875,
            "busy_slots": [],
            "appointment_trends": [],
            "all_booked_slots": "352",
            "average_booked_slots_time": 48.889499999999998181010596454143524169921875,
            "booking_distribution": {
                "self_booking": 14,
                "admin_panel_booking": 90,
                "walk_in_customer_booking": 4
            },
            "translation": [
                {
                    "id": 33,
                    "user_id": 39,
                    "language": "ar",
                    "first_Name": "\u0645\u0648\u0632\u0645\u0627\u0644",
                    "last_Name": "\u062d\u0633\u064a\u0646",
                    "created_at": "07-11-2024 10:59:33",
                    "updated_at": "07-11-2024 10:59:33"
                }
            ]
        },
        {
            "id": 36,
            "business_id": 2,
            "first_Name": "Namul",
            "last_Name": "Islam",
            "phone": "01555555555",
            "image": null,
            "is_walk_in_customer": 0,
            "address_line_1": null,
            "address_line_2": null,
            "country": null,
            "city": null,
            "postcode": null,
            "lat": null,
            "long": null,
            "email": "nazmul_expert@gmail.com",
            "stripe_id": null,
            "email_verified_at": "04-11-2024 16:40:59",
            "is_active": "1",
            "created_by": null,
            "login_attempts": 0,
            "last_failed_login_attempt_at": null,
            "background_image": null,
            "deleted_at": null,
            "created_at": "04-11-2024 16:40:59",
            "updated_at": "09-11-2024 15:52:08",
            "weekly_minimum_days": 6,
            "weekly_minimum_hours": 48,
            "this_month_revenue": 0,
            "last_month_revenue": 0,
            "total_bookings": "41",
            "upcoming_bookings_today": [],
            "upcoming_bookings": [],
            "all_services": [
                {
                    "id": 381,
                    "name": "Aromatherapy Massage",
                    "description": "Combines massage with the use of essential oils to boost physical and emotional well-being",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:22:20",
                    "updated_at": "01-11-2024 09:50:55",
                    "default_price": 40,
                    "price": "40.00"
                },
                {
                    "id": 383,
                    "name": "Classic European Facial",
                    "description": "A deep-cleansing facial that exfoliates, extracts impurities, and nourishes the skin, leaving it smooth and refreshed",
                    "service_id": 29,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 45,
                    "deleted_at": null,
                    "created_at": "01-11-2024 10:38:44",
                    "updated_at": "01-11-2024 10:38:44",
                    "default_price": 50,
                    "price": "50.00"
                },
                {
                    "id": 379,
                    "name": "Deep Tissue Massage",
                    "description": "Targets deeper muscle layers, perfect for chronic pain and muscle tension by applying more intense pressure",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:21:04",
                    "updated_at": "01-11-2024 09:53:58",
                    "default_price": 45,
                    "price": "45.00"
                },
                {
                    "id": 380,
                    "name": "Hot Stone Massage",
                    "description": "Heated stones are placed on key points of the body, enhancing relaxation and easing muscle stiffness",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:21:48",
                    "updated_at": "01-11-2024 09:54:13",
                    "default_price": 20,
                    "price": "20.00"
                },
                {
                    "id": 378,
                    "name": "Swedish Massage",
                    "description": "A relaxing, full-body massage that uses light to medium pressure, promoting relaxation and stress relief",
                    "service_id": 24,
                    "is_fixed_price": 1,
                    "business_id": 2,
                    "service_time_in_minute": 30,
                    "deleted_at": null,
                    "created_at": "31-10-2024 14:20:29",
                    "updated_at": "01-11-2024 09:54:36",
                    "default_price": 25,
                    "price": "25.00"
                }
            ],
            "average_rating": 0,
            "bookings": {
                "all": 4,
                "pending": 3,
                "confirmed": 0,
                "check_in": 1,
                "rejected_by_client": 0,
                "rejected_by_garage_owner": 0,
                "arrived": 0,
                "converted_to_job": 0
            },
            "revenue": 135,
            "busy_slots": [],
            "appointment_trends": [],
            "all_booked_slots": "352",
            "average_booked_slots_time": 48.889499999999998181010596454143524169921875,
            "booking_distribution": {
                "self_booking": 14,
                "admin_panel_booking": 90,
                "walk_in_customer_booking": 4
            },
            "translation": [
                {
                    "id": 27,
                    "user_id": 36,
                    "language": "ar",
                    "first_Name": "\u0646\u0627\u0645\u0648\u0644",
                    "last_Name": "\u0627\u0644\u0625\u0633\u0644\u0627\u0645",
                    "created_at": "04-11-2024 16:41:00",
                    "updated_at": "04-11-2024 16:41:00"
                }
            ]
        }
    ]
}
